# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/action_buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(200, 34)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_view = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view.sizePolicy().hasHeightForWidth())
        self.btn_view.setSizePolicy(sizePolicy)
        self.btn_view.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_view.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_view.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color: rgb(40, 167, 69);\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(115, 210, 22);\n"
"}\n"
"QPushButton::pressed{\n"
"    border: 1px solid rgb(111, 162, 28);\n"
"}")
        self.btn_view.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/assets/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_view.setIcon(icon)
        self.btn_view.setIconSize(QtCore.QSize(16, 16))
        self.btn_view.setObjectName("btn_view")
        self.horizontalLayout.addWidget(self.btn_view)
        self.btn_done = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_done.sizePolicy().hasHeightForWidth())
        self.btn_done.setSizePolicy(sizePolicy)
        self.btn_done.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_done.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_done.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color: rgb(5, 40, 170);\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(15, 156, 251);\n"
"}\n"
"QPushButton::pressed{\n"
"    border: 1px solid rgb(111, 162, 28);\n"
"}")
        self.btn_done.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/assets/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_done.setIcon(icon1)
        self.btn_done.setIconSize(QtCore.QSize(16, 16))
        self.btn_done.setObjectName("btn_done")
        self.horizontalLayout.addWidget(self.btn_done)
        self.btn_edit = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_edit.sizePolicy().hasHeightForWidth())
        self.btn_edit.setSizePolicy(sizePolicy)
        self.btn_edit.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_edit.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_edit.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color: rgb(245, 121, 0);\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(252, 175, 62);\n"
"}\n"
"QPushButton::pressed{\n"
"    border: 1px solid rgb(111, 162, 28);\n"
"}")
        self.btn_edit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/assets/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon2)
        self.btn_edit.setIconSize(QtCore.QSize(16, 16))
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.btn_delete = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete.sizePolicy().hasHeightForWidth())
        self.btn_delete.setSizePolicy(sizePolicy)
        self.btn_delete.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_delete.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_delete.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color: rgb(204, 0, 0);\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(239, 41, 41);\n"
"}\n"
"QPushButton::pressed{\n"
"    border: 1px solid rgb(111, 162, 28);\n"
"}")
        self.btn_delete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/assets/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon3)
        self.btn_delete.setIconSize(QtCore.QSize(16, 16))
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.btn_print = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_print.sizePolicy().hasHeightForWidth())
        self.btn_print.setSizePolicy(sizePolicy)
        self.btn_print.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_print.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_print.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color: rgb(15, 156, 251);\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(114, 159, 207);\n"
"}\n"
"QPushButton::pressed{\n"
"    border: 1px solid rgb(111, 162, 28);\n"
"}")
        self.btn_print.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/assets/printer-oq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_print.setIcon(icon4)
        self.btn_print.setIconSize(QtCore.QSize(16, 16))
        self.btn_print.setObjectName("btn_print")
        self.horizontalLayout.addWidget(self.btn_print)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
