# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_client_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 380)
        Dialog.setMinimumSize(QtCore.QSize(400, 0))
        Dialog.setMaximumSize(QtCore.QSize(400, 16777215))
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"    border:1px solid #333;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"    border:1px solid rgb(53, 132, 228);\n"
"}")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_8.addWidget(self.lineEdit_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"    border:1px solid #333;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"    border:1px solid rgb(53, 132, 228);\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_7.addWidget(self.lineEdit_7)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"    border:1px solid #333;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"    border:1px solid rgb(53, 132, 228);\n"
"}")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_9.addWidget(self.lineEdit_9)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    padding:10px;\n"
"    color:#fff;\n"
"    background-color: rgb(224, 27, 36);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(246, 97, 81);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    padding:10px;\n"
"    color:#fff;\n"
"    background-color: rgb(53, 132, 228);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(98, 160, 234);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Мижоз қўшиш"))
        self.label_8.setText(_translate("Dialog", "Исм Фамиля"))
        self.lineEdit_8.setPlaceholderText(_translate("Dialog", "Исм Фамиля"))
        self.label_7.setText(_translate("Dialog", "Компания"))
        self.lineEdit_7.setPlaceholderText(_translate("Dialog", "Компания"))
        self.label_9.setText(_translate("Dialog", "Телефон рақам"))
        self.lineEdit_9.setPlaceholderText(_translate("Dialog", "Телефон рақам"))
        self.pushButton_6.setText(_translate("Dialog", "Бекор қилиш"))
        self.pushButton_7.setText(_translate("Dialog", "Қўшиш"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
