# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 720)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_frame = QtWidgets.QFrame(self.centralwidget)
        self.sidebar_frame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.sidebar_frame.setStyleSheet("#sidebar_frame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}")
        self.sidebar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar_frame.setObjectName("sidebar_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sidebar_logo_frame = QtWidgets.QFrame(self.sidebar_frame)
        self.sidebar_logo_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.sidebar_logo_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.sidebar_logo_frame.setStyleSheet("#sidebar_logo_frame{\n"
"    border:none;\n"
"}")
        self.sidebar_logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar_logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar_logo_frame.setObjectName("sidebar_logo_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.sidebar_logo_frame)
        self.gridLayout.setContentsMargins(30, 20, 80, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.sidebar_logo_frame)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/assets/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.sidebar_logo_frame)
        self.sidebar_menu_frame = QtWidgets.QFrame(self.sidebar_frame)
        self.sidebar_menu_frame.setStyleSheet("#sidebar_menu_frame{\n"
"    border:none;\n"
"}\n"
"\n"
"#sidebar_menu_frame .QPushButton{\n"
"    border:none;\n"
"    font-weight: 500;\n"
"    font-size: 16px;\n"
"    line-height: 27px;\n"
"    color: #1B252E;\n"
"    height:40px;\n"
"    border-radius:10px;\n"
"    text-align:left;\n"
"    padding-left:40px;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"#sidebar_menu_frame QPushButton::hover{\n"
"    background-color:#006CFE;\n"
"    color:#FFF;\n"
"}\n"
"\n"
"")
        self.sidebar_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar_menu_frame.setObjectName("sidebar_menu_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar_menu_frame)
        self.verticalLayout_2.setContentsMargins(20, 10, 15, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_savdo = QtWidgets.QPushButton(self.sidebar_menu_frame)
        self.btn_savdo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_savdo.setStyleSheet("QPushButton{\n"
"    background-image: url(:/newPrefix/assets/savdo.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/assets/savdo-white.png);\n"
"}")
        self.btn_savdo.setObjectName("btn_savdo")
        self.verticalLayout_2.addWidget(self.btn_savdo)
        self.btn_client = QtWidgets.QPushButton(self.sidebar_menu_frame)
        self.btn_client.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_client.setStyleSheet("QPushButton{\n"
"    background-image: url(:/newPrefix/assets/client.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/assets/client-white.png);\n"
"}")
        self.btn_client.setObjectName("btn_client")
        self.verticalLayout_2.addWidget(self.btn_client)
        self.btn_product = QtWidgets.QPushButton(self.sidebar_menu_frame)
        self.btn_product.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_product.setStyleSheet("QPushButton{\n"
"    background-image: url(:/newPrefix/assets/product.png);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/assets/product-white.png);\n"
"}")
        self.btn_product.setObjectName("btn_product")
        self.verticalLayout_2.addWidget(self.btn_product)
        self.btn_savdolar = QtWidgets.QPushButton(self.sidebar_menu_frame)
        self.btn_savdolar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_savdolar.setStyleSheet("QPushButton{\n"
"    background-image: url(:/newPrefix/assets/list.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/assets/list-white.png);\n"
"}")
        self.btn_savdolar.setObjectName("btn_savdolar")
        self.verticalLayout_2.addWidget(self.btn_savdolar)
        self.btn_dollor = QtWidgets.QPushButton(self.sidebar_menu_frame)
        self.btn_dollor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dollor.setStyleSheet("QPushButton{\n"
"    background-image: url(:/newPrefix/assets/dollor.png);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/assets/dollor-white.png);\n"
"}")
        self.btn_dollor.setObjectName("btn_dollor")
        self.verticalLayout_2.addWidget(self.btn_dollor)
        spacerItem = QtWidgets.QSpacerItem(20, 417, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.sidebar_menu_frame)
        self.horizontalLayout.addWidget(self.sidebar_frame)
        self.main_stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.main_stack.setStyleSheet("#main_stack{\n"
"    border:none;\n"
"    background-color: rgb(246, 247, 249);\n"
"}")
        self.main_stack.setObjectName("main_stack")
        self.page_savdo = QtWidgets.QWidget()
        self.page_savdo.setObjectName("page_savdo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_savdo)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.page_savdo)
        self.frame.setMinimumSize(QtCore.QSize(0, 120))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame.setStyleSheet("#frame{\n"
"    border:none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(25, 8, 20, 8)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 80))
        self.frame_3.setMaximumSize(QtCore.QSize(300, 100))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(5, 10, 5, 15)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: #F2F3F7;\n"
"    padding-left:8px;\n"
"    padding-right: 30px;\n"
"color:#797979;\n"
"    background-image: url(:/newPrefix/assets/search.png);\n"
"    background-repeat:no-repeat;\n"
"    background-position: right center;\n"
"\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(220, 80))
        self.frame_4.setMaximumSize(QtCore.QSize(300, 100))
        self.frame_4.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(5, 10, 5, 15)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 36))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 36))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    border:none;\n"
"    background-color:#F2F3F7;\n"
"    color:#1B252E;\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"subcontrol-origin: padding; \n"
"subcontrol-position: top right;\n"
"width: 20px; \n"
"border-top-right-radius: 3px; \n"
"border-bottom-right-radius: 3px;}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/newPrefix/assets/down-arrow.png);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(160, 80))
        self.frame_5.setMaximumSize(QtCore.QSize(160, 100))
        self.frame_5.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    background-color:#2FB4FF;\n"
"color:#fff;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setMinimumSize(QtCore.QSize(160, 80))
        self.frame_6.setMaximumSize(QtCore.QSize(160, 100))
        self.frame_6.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    background-color:#446FDE;\n"
"color:#fff;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_2.addWidget(self.frame_6)
        spacerItem1 = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.page_savdo)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border:none;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setContentsMargins(25, 10, 20, 10)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px solid rgba(102, 102, 102, 0.5);\n"
"    border-collapse: collapse;\n"
"    \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #006CFE;\n"
"    padding: 4px;\n"
"    font-size: 14px;\n"
"    color:#fff;\n"
"    border-style: none;\n"
"    border-right:1px solid rgb(154, 153, 150);\n"
"}\n"
"\n"
" QScrollBar:horizontal {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        height: 10px;\n"
"        margin: 0px 21px 0 21px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:horizontal {\n"
"        background: #C0C0C0;\n"
"        min-width: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"QScrollBar:vertical {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        width: 10px;\n"
"        margin: 21px 0 21px 0;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        min-height: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.tableWidget)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_7.setStyleSheet("QFrame {\n"
"    border:none;\n"
"}\n"
"\n"
"QFrame QPushButton{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    padding:10px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(931, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color:#fff;\n"
"    background-color: rgb(53, 132, 228);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(98, 160, 234);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_7)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:#fff;\n"
"    background-color: rgb(7, 76, 27);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(46, 194, 126);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.main_stack.addWidget(self.page_savdo)
        self.page_client = QtWidgets.QWidget()
        self.page_client.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.page_client.setObjectName("page_client")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_client)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_10 = QtWidgets.QFrame(self.page_client)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_10.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setContentsMargins(25, 10, 20, 10)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setMinimumSize(QtCore.QSize(200, 80))
        self.frame_11.setMaximumSize(QtCore.QSize(400, 100))
        self.frame_11.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(5, 10, 5, 15)
        self.verticalLayout_10.setSpacing(3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.frame_11)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: #F2F3F7;\n"
"    padding-left:8px;\n"
"    padding-right: 30px;\n"
"color:#797979;\n"
"    background-image: url(:/newPrefix/assets/search.png);\n"
"    background-repeat:no-repeat;\n"
"    background-position: right center;\n"
"\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_10.addWidget(self.lineEdit_2)
        self.horizontalLayout_5.addWidget(self.frame_11)
        spacerItem3 = QtWidgets.QSpacerItem(578, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton{\n"
"    color:#fff;\n"
"    background-color: rgb(53, 132, 228);\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    padding:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(98, 160, 234);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_14.addWidget(self.frame_10)
        self.frame_8 = QtWidgets.QFrame(self.page_client)
        self.frame_8.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setContentsMargins(25, 10, 20, 10)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_8)
        self.tableWidget_2.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px solid rgba(102, 102, 102, 0.5);\n"
"    border-collapse: collapse;\n"
"    \n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #006CFE;\n"
"    padding: 4px;\n"
"    font-size: 14px;\n"
"    color:#fff;\n"
"    border-style: none;\n"
"    border-right:1px solid rgb(154, 153, 150);\n"
"}\n"
"\n"
" QScrollBar:horizontal {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        height: 10px;\n"
"        margin: 0px 21px 0 21px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:horizontal {\n"
"        background: #C0C0C0;\n"
"        min-width: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"QScrollBar:vertical {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        width: 10px;\n"
"        margin: 21px 0 21px 0;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        min-height: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"")
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.verticalLayout_9.addWidget(self.tableWidget_2)
        self.verticalLayout_14.addWidget(self.frame_8)
        self.main_stack.addWidget(self.page_client)
        self.page_savdolar = QtWidgets.QWidget()
        self.page_savdolar.setObjectName("page_savdolar")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_savdolar)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_14 = QtWidgets.QFrame(self.page_savdolar)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_14.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setContentsMargins(25, 10, 20, 10)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setMinimumSize(QtCore.QSize(200, 80))
        self.frame_15.setMaximumSize(QtCore.QSize(400, 100))
        self.frame_15.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_15.setContentsMargins(5, 10, 5, 15)
        self.verticalLayout_15.setSpacing(3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_10 = QtWidgets.QLabel(self.frame_15)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_15.addWidget(self.label_10)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: #F2F3F7;\n"
"    padding-left:8px;\n"
"    padding-right: 30px;\n"
"color:#797979;\n"
"    background-image: url(:/newPrefix/assets/search.png);\n"
"    background-repeat:no-repeat;\n"
"    background-position: right center;\n"
"\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_15.addWidget(self.lineEdit_4)
        self.horizontalLayout_7.addWidget(self.frame_15)
        spacerItem4 = QtWidgets.QSpacerItem(578, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_17.addWidget(self.frame_14)
        self.frame_16 = QtWidgets.QFrame(self.page_savdolar)
        self.frame_16.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_16.setContentsMargins(25, 10, 20, 10)
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_16)
        self.tableWidget_4.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px solid rgba(102, 102, 102, 0.5);\n"
"    border-collapse: collapse;\n"
"    \n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #006CFE;\n"
"    padding: 4px;\n"
"    font-size: 14px;\n"
"    color:#fff;\n"
"    border-style: none;\n"
"    border-right:1px solid rgb(154, 153, 150);\n"
"}\n"
"\n"
" QScrollBar:horizontal {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        height: 10px;\n"
"        margin: 0px 21px 0 21px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:horizontal {\n"
"        background: #C0C0C0;\n"
"        min-width: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"QScrollBar:vertical {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        width: 10px;\n"
"        margin: 21px 0 21px 0;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        min-height: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"")
        self.tableWidget_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_4.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_4.setRowCount(0)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.tableWidget_4.horizontalHeader().setVisible(False)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tableWidget_4)
        self.verticalLayout_17.addWidget(self.frame_16)
        self.main_stack.addWidget(self.page_savdolar)
        self.page_maxsulotlar = QtWidgets.QWidget()
        self.page_maxsulotlar.setObjectName("page_maxsulotlar")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_maxsulotlar)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_12 = QtWidgets.QFrame(self.page_maxsulotlar)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_12.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setContentsMargins(25, 10, 20, 10)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setMinimumSize(QtCore.QSize(200, 80))
        self.frame_13.setMaximumSize(QtCore.QSize(400, 100))
        self.frame_13.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setContentsMargins(5, 10, 5, 15)
        self.verticalLayout_11.setSpacing(3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: #F2F3F7;\n"
"    padding-left:8px;\n"
"    padding-right: 30px;\n"
"color:#797979;\n"
"    background-image: url(:/newPrefix/assets/search.png);\n"
"    background-repeat:no-repeat;\n"
"    background-position: right center;\n"
"\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_11.addWidget(self.lineEdit_3)
        self.horizontalLayout_6.addWidget(self.frame_13)
        spacerItem5 = QtWidgets.QSpacerItem(578, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("\n"
"QPushButton{\n"
"    color:#fff;\n"
"    background-color: rgb(53, 132, 228);\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    padding:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(98, 160, 234);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_13.addWidget(self.frame_12)
        self.frame_9 = QtWidgets.QFrame(self.page_maxsulotlar)
        self.frame_9.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_12.setContentsMargins(25, 10, 20, 10)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_9)
        self.tableWidget_3.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px solid rgba(102, 102, 102, 0.5);\n"
"    border-collapse: collapse;\n"
"    \n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #006CFE;\n"
"    padding: 4px;\n"
"    font-size: 14px;\n"
"    color:#fff;\n"
"    border-style: none;\n"
"    border-right:1px solid rgb(154, 153, 150);\n"
"}\n"
"\n"
" QScrollBar:horizontal {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        height: 10px;\n"
"        margin: 0px 21px 0 21px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:horizontal {\n"
"        background: #C0C0C0;\n"
"        min-width: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"QScrollBar:vertical {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        width: 10px;\n"
"        margin: 21px 0 21px 0;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        min-height: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"")
        self.tableWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        self.tableWidget_3.horizontalHeader().setVisible(True)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.tableWidget_3)
        self.verticalLayout_13.addWidget(self.frame_9)
        self.main_stack.addWidget(self.page_maxsulotlar)
        self.page_dollor = QtWidgets.QWidget()
        self.page_dollor.setObjectName("page_dollor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_dollor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.page_dollor)
        self.frame_24.setMinimumSize(QtCore.QSize(500, 250))
        self.frame_24.setStyleSheet("#frame_24{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QFrame{\n"
"    border:none;\n"
"}")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_24.setContentsMargins(25, 20, 20, 20)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_17 = QtWidgets.QLabel(self.frame_24)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_24.addWidget(self.label_17)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(10, -1, 20, 0)
        self.horizontalLayout_9.setSpacing(15)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_25 = QtWidgets.QFrame(self.frame_24)
        self.frame_25.setMinimumSize(QtCore.QSize(80, 120))
        self.frame_25.setMaximumSize(QtCore.QSize(80, 120))
        self.frame_25.setStyleSheet("")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_25)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_7.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_7.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border: 1px solid #D9D9D9;\n"
"    background-color:#fff;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:#fff;\n"
"    background-color: rgb(94, 92, 100);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.frame_24)
        self.frame_26.setMinimumSize(QtCore.QSize(220, 120))
        self.frame_26.setMaximumSize(QtCore.QSize(300, 120))
        self.frame_26.setStyleSheet("#frame_26{\n"
"border-radius: 15px;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.414, x2:0.9801, y2:0, stop:0 rgba(28, 54, 139, 255), stop:1 rgba(45, 77, 207, 255));\n"
"}")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_18 = QtWidgets.QLabel(self.frame_26)
        self.label_18.setAutoFillBackground(False)
        self.label_18.setStyleSheet("font-weight: 500;\n"
"font-size: 12px;\n"
"line-height: 22px;\n"
"color: #FFFFFF;\n"
"")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_25.addWidget(self.label_18)
        self.label_20 = QtWidgets.QLabel(self.frame_26)
        self.label_20.setStyleSheet("font-weight: 600;\n"
"font-size: 38px;\n"
"line-height: 40px;\n"
"color: #FFFFFF;")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_25.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.frame_26)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAutoFillBackground(False)
        self.label_21.setStyleSheet("font-weight: 500;\n"
"font-size: 12px;\n"
"line-height: 22px;\n"
"color: #FFFFFF;\n"
"text-align:right;\n"
"")
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_25.addWidget(self.label_21)
        self.horizontalLayout_9.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(self.frame_24)
        self.frame_27.setMinimumSize(QtCore.QSize(220, 120))
        self.frame_27.setMaximumSize(QtCore.QSize(300, 120))
        self.frame_27.setStyleSheet("#frame_27{\n"
"    border-radius:15px;\n"
"    background-color: rgb(94, 92, 100);\n"
"}")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_19 = QtWidgets.QLabel(self.frame_27)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setStyleSheet("font-weight: 500;\n"
"font-size: 12px;\n"
"line-height: 22px;\n"
"color: #FFFFFF;\n"
"")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_26.addWidget(self.label_19)
        self.label_23 = QtWidgets.QLabel(self.frame_27)
        self.label_23.setStyleSheet("font-weight: 600;\n"
"font-size: 38px;\n"
"line-height: 40px;\n"
"color: #FFFFFF;")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_26.addWidget(self.label_23)
        self.label_22 = QtWidgets.QLabel(self.frame_27)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setStyleSheet("font-weight: 500;\n"
"font-size: 12px;\n"
"line-height: 22px;\n"
"color: #FFFFFF;\n"
"text-align:right;\n"
"")
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_26.addWidget(self.label_22)
        self.horizontalLayout_9.addWidget(self.frame_27)
        self.verticalLayout_24.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem8)
        self.verticalLayout_24.setStretch(0, 1)
        self.verticalLayout_24.setStretch(1, 3)
        self.gridLayout_2.addWidget(self.frame_24, 1, 1, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(367, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 290, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 2, 2, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 1)
        self.gridLayout_2.setColumnMinimumWidth(1, 5)
        self.gridLayout_2.setColumnMinimumWidth(2, 3)
        self.gridLayout_2.setColumnMinimumWidth(3, 5)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setColumnStretch(2, 5)
        self.gridLayout_2.setColumnStretch(3, 4)
        self.main_stack.addWidget(self.page_dollor)
        self.page_shop_detail = QtWidgets.QWidget()
        self.page_shop_detail.setObjectName("page_shop_detail")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_shop_detail)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_19 = QtWidgets.QFrame(self.page_shop_detail)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_19.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_8.setContentsMargins(25, 8, 20, 8)
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setMinimumSize(QtCore.QSize(200, 80))
        self.frame_20.setMaximumSize(QtCore.QSize(300, 100))
        self.frame_20.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_19.setContentsMargins(5, 10, 5, 15)
        self.verticalLayout_19.setSpacing(3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.frame_20)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_19.addWidget(self.label_11)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: #F2F3F7;\n"
"    padding-left:8px;\n"
"    padding-right: 30px;\n"
"color:#797979;\n"
"    background-image: url(:/newPrefix/assets/search.png);\n"
"    background-repeat:no-repeat;\n"
"    background-position: right center;\n"
"\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_19.addWidget(self.lineEdit_5)
        self.horizontalLayout_8.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_19)
        self.frame_21.setMinimumSize(QtCore.QSize(220, 80))
        self.frame_21.setMaximumSize(QtCore.QSize(300, 100))
        self.frame_21.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_20.setContentsMargins(5, 10, 5, 15)
        self.verticalLayout_20.setSpacing(3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_12 = QtWidgets.QLabel(self.frame_21)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_20.addWidget(self.label_12)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_21)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 36))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 36))
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    border:none;\n"
"    background-color:#F2F3F7;\n"
"    color:#1B252E;\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"subcontrol-origin: padding; \n"
"subcontrol-position: top right;\n"
"width: 20px; \n"
"border-top-right-radius: 3px; \n"
"border-bottom-right-radius: 3px;}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/newPrefix/assets/down-arrow.png);\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_20.addWidget(self.comboBox_2)
        self.horizontalLayout_8.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_19)
        self.frame_22.setMinimumSize(QtCore.QSize(160, 80))
        self.frame_22.setMaximumSize(QtCore.QSize(160, 100))
        self.frame_22.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    background-color:#2FB4FF;\n"
"color:#fff;\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_13 = QtWidgets.QLabel(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_21.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_21.addWidget(self.label_14)
        self.horizontalLayout_8.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_19)
        self.frame_23.setMinimumSize(QtCore.QSize(160, 80))
        self.frame_23.setMaximumSize(QtCore.QSize(160, 100))
        self.frame_23.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    background-color:#446FDE;\n"
"color:#fff;\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_15 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_22.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_22.addWidget(self.label_16)
        self.horizontalLayout_8.addWidget(self.frame_23)
        spacerItem11 = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_23.addWidget(self.frame_19)
        self.frame_17 = QtWidgets.QFrame(self.page_shop_detail)
        self.frame_17.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_18.setContentsMargins(25, 10, 20, 10)
        self.verticalLayout_18.setSpacing(5)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.frame_17)
        self.tableWidget_5.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px solid rgba(102, 102, 102, 0.5);\n"
"    border-collapse: collapse;\n"
"    \n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #006CFE;\n"
"    padding: 4px;\n"
"    font-size: 14px;\n"
"    color:#fff;\n"
"    border-style: none;\n"
"    border-right:1px solid rgb(154, 153, 150);\n"
"}\n"
"\n"
" QScrollBar:horizontal {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        height: 10px;\n"
"        margin: 0px 21px 0 21px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:horizontal {\n"
"        background: #C0C0C0;\n"
"        min-width: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:horizontal {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"QScrollBar:vertical {\n"
"        border: none;\n"
"        background: #F5F5F5;\n"
"        width: 10px;\n"
"        margin: 21px 0 21px 0;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        min-height: 20px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"")
        self.tableWidget_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_5.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_5.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_5.setRowCount(0)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(10, item)
        self.tableWidget_5.horizontalHeader().setVisible(False)
        self.tableWidget_5.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_5.verticalHeader().setVisible(False)
        self.verticalLayout_18.addWidget(self.tableWidget_5)
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_18.setStyleSheet("QFrame {\n"
"    border:none;\n"
"}\n"
"\n"
"QFrame QPushButton{\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    padding:10px;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem12 = QtWidgets.QSpacerItem(931, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color:#fff;\n"
"    background-color: rgb(53, 132, 228);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(98, 160, 234);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color:#fff;\n"
"    background-color: rgb(7, 76, 27);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(46, 194, 126);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout_18.addWidget(self.frame_18)
        self.verticalLayout_23.addWidget(self.frame_17)
        self.main_stack.addWidget(self.page_shop_detail)
        self.horizontalLayout.addWidget(self.main_stack)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_savdo.setText(_translate("MainWindow", "Сотув"))
        self.btn_client.setText(_translate("MainWindow", "Мижозлар"))
        self.btn_product.setText(_translate("MainWindow", "Махсулотлар"))
        self.btn_savdolar.setText(_translate("MainWindow", "Савдолар"))
        self.btn_dollor.setText(_translate("MainWindow", "Доллор курси"))
        self.label.setText(_translate("MainWindow", "Қидириш"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Қидириш..."))
        self.label_3.setText(_translate("MainWindow", "Мижоз"))
        self.comboBox.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(3, _translate("MainWindow", "New Item"))
        self.label_4.setText(_translate("MainWindow", "Доллор курси"))
        self.label_5.setText(_translate("MainWindow", "11,400"))
        self.label_6.setText(_translate("MainWindow", "Умумий сумма"))
        self.label_7.setText(_translate("MainWindow", "12,540,600"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Махсулот"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "модел"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Бирлик"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Бренд"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ишлаб Чиқаручи"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Сони"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "$"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Нархи"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Сумма"))
        self.pushButton_2.setText(_translate("MainWindow", "Печат"))
        self.pushButton.setText(_translate("MainWindow", "Сақлаш"))
        self.label_8.setText(_translate("MainWindow", "Қидириш"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Қидириш..."))
        self.pushButton_5.setText(_translate("MainWindow", "+"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Исм Фамиля"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Компания"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Телефон рақам"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Тахрирлаш"))
        self.label_10.setText(_translate("MainWindow", "Қидириш"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Қидириш..."))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Мижоз"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Сумма"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Сана"))
        self.label_9.setText(_translate("MainWindow", "Қидириш"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Қидириш..."))
        self.pushButton_6.setText(_translate("MainWindow", "+"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Номи"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Бренд"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Модел"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Иш / чмқарувчи"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Нархи комп $"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Нархи дона $"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Тахрирлаш"))
        self.label_17.setText(_translate("MainWindow", "Доллор курси"))
        self.pushButton_7.setText(_translate("MainWindow", "+"))
        self.label_18.setText(_translate("MainWindow", "Хозирги курс"))
        self.label_20.setText(_translate("MainWindow", "11, 800 s"))
        self.label_21.setText(_translate("MainWindow", "02.02.2023"))
        self.label_19.setText(_translate("MainWindow", "Эски курс"))
        self.label_23.setText(_translate("MainWindow", "11, 800 s"))
        self.label_22.setText(_translate("MainWindow", "02.02.2023"))
        self.label_11.setText(_translate("MainWindow", "Қидириш"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Қидириш..."))
        self.label_12.setText(_translate("MainWindow", "Мижоз"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "New Item"))
        self.label_13.setText(_translate("MainWindow", "Доллор курси"))
        self.label_14.setText(_translate("MainWindow", "11,400"))
        self.label_15.setText(_translate("MainWindow", "Умумий сумма"))
        self.label_16.setText(_translate("MainWindow", "12,540,600"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Махсулот"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "модел"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Бирлик"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Бренд"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ишлаб Чиқаручи"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Сони"))
        item = self.tableWidget_5.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "$"))
        item = self.tableWidget_5.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Нархи"))
        item = self.tableWidget_5.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Сумма"))
        self.pushButton_3.setText(_translate("MainWindow", "Печат"))
        self.pushButton_4.setText(_translate("MainWindow", "Сақлаш"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
