# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/search_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(750, 263)
        Frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 0px 0 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(111, 162, 28);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 10px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 0px 0 0px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(111, 162, 28);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }")
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.table_search = QtWidgets.QTableWidget(Frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.table_search.setFont(font)
        self.table_search.setStyleSheet("QTableWidget{\n"
"    border:1px solid rgba(102, 102, 102, 0.5);\n"
"    border-radius:7px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QHeaderView::section { \n"
"    padding:7px;\n"
"    font-size:12px;\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(111, 162, 28);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.table_search.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_search.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.table_search.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_search.setRowCount(0)
        self.table_search.setObjectName("table_search")
        self.table_search.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.table_search.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        item.setFont(font)
        self.table_search.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        item.setFont(font)
        self.table_search.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        item.setFont(font)
        self.table_search.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        item.setFont(font)
        self.table_search.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_search.setHorizontalHeaderItem(5, item)
        self.table_search.horizontalHeader().setVisible(True)
        self.table_search.horizontalHeader().setCascadingSectionResizes(True)
        self.table_search.horizontalHeader().setDefaultSectionSize(120)
        self.table_search.horizontalHeader().setSortIndicatorShown(False)
        self.table_search.horizontalHeader().setStretchLastSection(False)
        self.table_search.verticalHeader().setVisible(False)
        self.table_search.verticalHeader().setDefaultSectionSize(30)
        self.table_search.verticalHeader().setHighlightSections(False)
        self.table_search.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.table_search, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        item = self.table_search.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "Id"))
        item = self.table_search.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "Махсулот"))
        item = self.table_search.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "Бренд"))
        item = self.table_search.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "Модел"))
        item = self.table_search.horizontalHeaderItem(4)
        item.setText(_translate("Frame", "Завод"))
        item = self.table_search.horizontalHeaderItem(5)
        item.setText(_translate("Frame", "Нархи"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
